[[ROCmLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3098966c93c8f7807ddf58a4d6a98e620457381c"
libc = "glibc"
os = "linux"

    [[ROCmLLVM.download]]
    sha256 = "d0e3aec55c6928c52a998437019e4a7e924723561b3ddefc441692044dbf467f"
    url = "https://github.com/JuliaBinaryWrappers/ROCmLLVM_jll.jl/releases/download/ROCmLLVM-v4.5.2+0/ROCmLLVM.v4.5.2.x86_64-linux-gnu-cxx11.tar.gz"
[[ROCmLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1174f90415753cb5abf199573817aef00fc953c9"
libc = "musl"
os = "linux"

    [[ROCmLLVM.download]]
    sha256 = "92efad1e73e4e136b6248a2e118f518f7d33d6e7294624e6147200a68a9dea65"
    url = "https://github.com/JuliaBinaryWrappers/ROCmLLVM_jll.jl/releases/download/ROCmLLVM-v4.5.2+0/ROCmLLVM.v4.5.2.x86_64-linux-musl-cxx11.tar.gz"
