[[ROCmLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "120561db10a16598ec274bc172d1b9ac018ea97f"
libc = "glibc"
os = "linux"

    [[ROCmLLVM.download]]
    sha256 = "e965c332200e04b830ca9478adc836cd63d50cc12abbeeae68728aa30f574343"
    url = "https://github.com/JuliaBinaryWrappers/ROCmLLVM_jll.jl/releases/download/ROCmLLVM-v5.4.4+0/ROCmLLVM.v5.4.4.x86_64-linux-gnu-cxx11.tar.gz"
[[ROCmLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b5e6c491f1d2baf7e185a6ee97d4591739cb3a37"
libc = "musl"
os = "linux"

    [[ROCmLLVM.download]]
    sha256 = "600bbe3bcfc9eb9899f0ef1a2ceec6396b7e515109b524f3ff5629b98be90a0f"
    url = "https://github.com/JuliaBinaryWrappers/ROCmLLVM_jll.jl/releases/download/ROCmLLVM-v5.4.4+0/ROCmLLVM.v5.4.4.x86_64-linux-musl-cxx11.tar.gz"
