[[ROCmLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cd839453e34e1ae65cff379eb5b34dcddd2a2c22"
libc = "glibc"
os = "linux"

    [[ROCmLLVM.download]]
    sha256 = "50e3a1d9c86a62e4dfa266076b5cc580a59cc267cd0f4a1f6b99b9597aa53d4c"
    url = "https://github.com/JuliaBinaryWrappers/ROCmLLVM_jll.jl/releases/download/ROCmLLVM-v5.5.1+0/ROCmLLVM.v5.5.1.x86_64-linux-gnu-cxx11.tar.gz"
[[ROCmLLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "576f27fdadddb312298e3622e1d31a5d8413018c"
libc = "musl"
os = "linux"

    [[ROCmLLVM.download]]
    sha256 = "3330ad4d719e6378f8e913b7b66e8ae426e5542783f39ad923aa4bd490a8d9ac"
    url = "https://github.com/JuliaBinaryWrappers/ROCmLLVM_jll.jl/releases/download/ROCmLLVM-v5.5.1+0/ROCmLLVM.v5.5.1.x86_64-linux-musl-cxx11.tar.gz"
